site_name: Computer Organization Fall 2024 @NCKUEE
theme:
  name: material
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - search.relevance
    - content.tabs
    - content.code.annotation
    - content.code.copy
    - content.footnotes
    - content.images
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: deep purple
      accent: blue
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: deep purple
      accent: blue
extra_css:
  - css/custom.css
extra_javascript:
  - js/custom.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - js/mathjax.js # mathjax
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # mathjax
plugins:
  - social
  - search
extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/eemomolleyball?igsh=MnI5cnM0YnljcnEy
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span 
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex: # mathjax
      generic: true
copyright: |
  &copy; Create by <a href=""  target="_blank" rel="noopener">Jieum.C</a> in 2024 ♥ 
nav:
  - 首頁: 
    - Index: index.md
    # - Announcement: 
        # - updates: announce/update.md
        # - a0x000: announce/a0x000.md
  - Lab material:
      - Overview: labs/lab_overview.md
      - Lab 0 - How To Ask Questions The Smart Way: labs/lab0.md
      - Lab 1 - C Programmin and Compilation Flow: labs/lab1.md
      - Lab 2 - Simple RISC-V ISA Simulator with RV64I: labs/lab2.md
      - Lab 3 - Bare-metal Runtime Environment and RISC-V Assembly Programming: labs/lab3.md
      - Lab 4 - RTL Programming Review using SystemVerilog: labs/lab4.md
      - Lab 5 - Single-Cycle CPU Design and Differential Testing: labs/lab5.md
      - Lab 6 - Bus Protocol and Arbitration: labs/lab6.md
      - Lab 7 - Pipeline CPU and Simple Cache Design: labs/lab7.md
      - Lab 8 - Deep Dive into Memory System: labs/lab8.md
      - Lab 9 - SIMD Accelerator and GEMM Kernel Design: labs/lab9.md
  - Tools Guide:
      - Basic Linux Command: tools/linux_cmd.md
      - Git Tutorial: tools/git_cmd.md
      - Docker Tutorial: tools/docker.md
      - Markdown Tutorial: tools/markdown.md
      - Gitla & Mattermost: tools/gitlab_ov.md
      - Useful CLI Tools: tools/cli_tools.md
  - RTL Programming:
    - Introduction to Verilog and RTL Programming: rtl/verilog.md
    - From Verilog to SystemVerilog for Hardware Designing: rtl/sv.md
    - SystemVerilog Assertion (SVA): rtl/sva.md
    - Chisel HDL: rtl/chisel.md
    - _Verilog: rtl/_verilog.md
  - 補充資料: references.md
  # - About MkDocs: mkdocs.md
